### ISSUE TITLE
Consider adding a Tag and a Release

### ISSUE THREAD

**Issue by ddribin** [danpodeanu/udp-redirect#3]
Hello! Thank you for making this. I have found it very useful to forward Minecraft traffic.

Would you consider adding a Tag and a Release? This would make it easier to install via package management software like [Homebrew](https://brew.sh) on macOS.

**Comment by danpodeanu** [comment]
Good suggestion, thank you. I have published https://github.com/danpodeanu/udp-redirect/releases/tag/v1.0.0 which includes a Homebrew formula.

I will be submitting the formula to the Homebrew official repo, although there is a fair chance it will not be accepted. I will update this issue once I hear back.

```
% brew audit --strict --new --online udp-redirect 
udp-redirect
  * GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)
Error: 1 problem in 1 formula detected.
```

**Comment by ddribin** [comment]
Great, thank you! I already added this into my personal Homebrew tap, so I will update it to use `v.1.0.0`:

https://github.com/ddribin/homebrew-extras/blob/master/Formula/udp-redirect.rb

If they accept it, I'll be able to remove it.
